SELECT
  A.ID,
  A.ID_MASSIVA,
  A.ID_TP_ACAO,
  B.DESC_TP_ACAO,
  (
    CASE
      WHEN A.ID_TP_ACAO = 1 THEN TO_CHAR (DT_ABERTURA, 'dd/mm/yyyy hh24:mi:ss')
      ELSE TO_CHAR (
        DT_MANUTENCAO_PROGRAMADA,
        'dd/mm/yyyy hh24:mi:ss'
      )
    END
  ) DT_ABERTURA,
  A.TIPO,
  A.STATUS,
  A.MSAN,
  A.PAR_INI,
  A.PAR_FIM,
  A.UF,
  A.CIDADE,
  A.ID_TP_FALHA,
  (
    CASE
      WHEN A.ID_TP_FALHA = 0 THEN C.DESC_TP_MANUTENCAO
      ELSE D.DESC_TP_FALHA
    END
  ) DESC_TP_FALHA,
  A.ID_AREA,
  E.DESC_AREA,
  A.PRAZO,
  (
    CASE
      WHEN TIPO = 'S' THEN (
        CASE
          WHEN SYSDATE >= (A.DT_ABERTURA (1 / 12)) THEN 'S'
          WHEN SYSDATE >= (A.DT_ABERTURA (1 / 24 * 1.5)) THEN 'A1'
          WHEN SYSDATE >= (A.DT_ABERTURA (1 / 24)) THEN 'A2'
          ELSE 'N'
        END
      )
      ELSE (
        CASE
          WHEN SYSDATE > (A.PRAZO) THEN 'S'
          WHEN SYSDATE > (A.PRAZO - (1 / 24)) THEN 'A1'
          WHEN SYSDATE > (A.PRAZO - (2 / 24)) THEN 'A2'
          ELSE 'N'
        END
      )
    END
  ) EXPIRADO,
  EMPREITEIRA,
  NVL2(QTD_CLIENTES, TO_CHAR(QTD_CLIENTES), '?') AS QTD_CLIENTES,
  TO_CHAR (
    DT_INI_INDISPONIBILIDADE,
    'dd/mm/yyyy hh24:mi:ss'
  ) AS DT_INI_INDISPONIBILIDADE,
  TO_CHAR (
    DT_FIM_INDISPONIBILIDADE,
    'dd/mm/yyyy hh24:mi:ss'
  ) AS DT_FIM_INDISPONIBILIDADE,
  NVL(C.FLAG_INDISPONIBILIDADE, 1) INDISPONIBILIDADE,
  A.OBSERVACAO
FROM
  CICOP.COP_APP_METAL_MASSIVA A,
  CICOP.COP_APP_METAL_TP_ACAO B,
  CICOP.COP_APP_METAL_TP_MANUTENCAO C,
  CICOP.COP_APP_METAL_TP_FALHA D,
  CICOP.COP_APP_METAL_AREA E
WHERE
  A.STATUS = 0
  AND B.ID_TP_ACAO = A.ID_TP_ACAO
  AND C.ID_TP_MANUTENCAO () = A.ID_TP_MANUTENCAO
  AND D.ID_TP_FALHA () = A.ID_TP_FALHA
  AND E.ID_AREA = A.ID_AREA
ORDER BY
  A.DT_ABERTURA;